# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'video' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for video

  pod 'MJRefresh', '~>3.1.12'
  pod 'Alamofire', '~>4.0'
  pod 'AlamofireObjectMapper'

  pod 'SwiftyJSON'
  pod "Qiniu", :git => 'https://github.com/qiniu/objc-sdk.git', :branch => 'AFNetworking-3.x'
  pod 'RealmSwift', '2.8.0'
  pod 'UMengAnalytics-NO-IDFA', '~> 4.1.1'
  pod 'AFNetworking', '~> 3.1.0'
  pod "Qiniu", :git => 'https://github.com/qiniu/objc-sdk.git', :branch => 'AFNetworking-3.x'
  pod 'DZNEmptyDataSet', '~> 1.8.1'
  pod 'RSKImageCropper', '~> 1.6.1'
  pod 'SDWebImage', '~> 3.8.2'
  pod 'WeChat_SDK', '~> 1.7.2.1'
  pod 'SnapKit', '~> 3.0.2'
  pod 'ResponsiveLabel', '~> 1.0.11'

end
